AllCops:
  TargetRubyVersion: 2.3

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/CaseIndentation:
  Enabled: false

Style/ElseAlignment:
  Enabled: false

#Metrics/MethodLength:
#  Enabled: false
#
#Metrics/ClassLength:
#  Enabled: false
#
#Metrics/ModuleLength:
#  Enabled: false
#
#Metrics/LineLength:
#  Max: 120
#
#Metrics/CyclomaticComplexity:
#  Enabled: false
#
#Lint/NestedMethodDefinition:
#  Enabled: false
#
#Lint/RescueException:
#  Enabled: false
#
#Lint/EndAlignment:
#  Enabled: false